participant: Fluid_Solver

precice-config-file: ../precice-config.xml

interfaces:
- mesh: Fluid_CellCenters
  locations: faceCenters
  patches:
  - bottomWall
  write-data: Force
- mesh: Fluid_Nodes
  locations: faceNodes
  patches:
  - bottomWall
  read-data: DisplacementDelta

FSIenabled: true

